/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangeLog: typeof import('./../components/ChangeLog.vue')['default']
    InstalledView: typeof import('./../components/InstalledView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdatedView: typeof import('./../components/UpdatedView.vue')['default']
  }
}
